---
- name: Reboot Linux systems
  hosts: Linux # Specify the appropriate group or hosts
  become: yes  # Ensure privilege escalation for rebooting
  vars_files:
    - vault.yml
  gather_facts: no
  tasks:

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 180  # Set to 3 minutes (180 seconds) for the reboot timeout
      ignore_errors: yes  # Ignore any errors in case of issues during reboot

    - name: Wait for the system to come back online
      ansible.builtin.wait_for:
        port: 22  # Wait for SSH to be available
        host: "{{ inventory_hostname }}"
        delay: 30  # Wait for 30 seconds before starting to check SSH
        timeout: 180  # 3-minute (180 seconds) timeout for SSH availability
      delegate_to: localhost  # Run the check on the control node
